module Verifalia
  module EmailValidations
    module EntryStatus
      AT_SIGN_NOT_FOUND: String
      CATCH_ALL_CONNECTION_FAILURE: String
      CATCH_ALL_VALIDATION_TIMEOUT: String
      DNS_CONNECTION_FAILURE: String
      DNS_QUERY_TIMEOUT: String
      DOMAIN_DOES_NOT_EXIST: String
      DOMAIN_HAS_NULL_MX: String
      DOMAIN_IS_MISCONFIGURED: String
      DOMAIN_IS_WELL_KNOWN_DEA: String
      DOMAIN_PART_COMPLIANCY_FAILURE: String
      DOUBLE_DOT_SEQUENCE: String
      DUPLICATE: String
      INVALID_ADDRESS_LENGTH: String
      INVALID_CHARACTER_IN_SEQUENCE: String
      INVALID_EMPTY_QUOTED_WORD: String
      INVALID_FOLDING_WHITE_SPACE_SEQUENCE: String
      INVALID_LOCAL_PART_LENGTH: String
      INVALID_WORD_BOUNDARY_START: String
      ISP_SPECIFIC_SYNTAX_FAILURE: String
      LOCAL_END_POINT_REJECTED: String
      LOCAL_PART_IS_WELL_KNOWN_ROLE_ACCOUNT: String
      LOCAL_SENDER_ADDRESS_REJECTED: String
      MAILBOX_CONNECTION_FAILURE: String
      MAILBOX_DOES_NOT_EXIST: String
      MAILBOX_HAS_INSUFFICIENT_STORAGE: String
      MAILBOX_IS_DEA: String
      MAILBOX_TEMPORARILY_UNAVAILABLE: String
      MAILBOX_VALIDATION_TIMEOUT: String
      MAIL_EXCHANGER_IS_HONEYPOT: String
      MAIL_EXCHANGER_IS_PARKED: String
      MAIL_EXCHANGER_IS_WELL_KNOWN_DEA: String
      OVERRIDE_MATCH: String
      SERVER_DOES_NOT_SUPPORT_INTERNATIONAL_MAILBOXES: String
      SERVER_IS_CATCH_ALL: String
      SERVER_TEMPORARILY_UNAVAILABLE: String
      SMTP_CONNECTION_FAILURE: String
      SMTP_CONNECTION_TIMEOUT: String
      SMTP_DIALOG_ERROR: String
      SUCCESS: String
      UNACCEPTABLE_DOMAIN_LITERAL: String
      UNBALANCED_COMMENT_PARENTHESIS: String
      UNEXPECTED_QUOTED_PAIR_SEQUENCE: String
      UNHANDLED_EXCEPTION: String
      UNMATCHED_QUOTED_PAIR: String
    end
  end
end
